import React  from 'react';
// import conenct from react-redux
...

// import fetchLocations from modules
...

// import LocationsPage from components
...

// export connectedLocationPage (pass fetchLocations)
...
